### ISSUE TITLE
Example on get_shortest_path_to_object_type

### ISSUE THREAD

**Issue by ChongjianGE** [zkytony/thortils#2]
Hi @zkytony 
Thanks for the wonderful project.
I am currently implementing the `get_shortest_path_to_object_type` fucntion to get the valid path for navigation. However, I found the current code breaks down when run the function. Could you give me an example on how to run the `get_shortest_path_to_object_type` function?

**Comment by zkytony** [comment]
Oops. Not sure why I didn't see this before... It's been a while. I couldn't find an example for `get_shortest_path_to_object_type` but I do have an example for `get_shortest_path_to_object_type` [here in another repo](https://github.com/zkytony/cos-pomdp/blob/1e3c7fe940a2165b5c5c384ebf047e8139d437ec/cospomdp_apps/thor/agent/optimal.py#L142).   It's used as part of an A* planner implementation. See video for examples: 
* https://www.youtube.com/watch?v=msy432F3CvE (this one should work)
* https://www.youtube.com/watch?v=niZY9y0z3vQ (object in container; this one doesn't always work)

Hope you've resolved your original issue, and hope this answer is helpful for others.

**Comment by zkytony** [comment]
The idea for `get_shortest_path_to_object_type` should be similar (just first fetch the object instance with the type closest to the robot, then use `get_shortest_path_to_object_type` for that instance).
