### ISSUE TITLE
Running Thortils in a Headless Setup

### ISSUE THREAD

**Issue by Ayush8120** [zkytony/thortils#3]
Hi!
Thanks for this wonderful piece of work. I was wondering if there was any way by which I could run this on a HEADLESS setup? I saw a variable called `headless` in `launch_controller` function, but couldn't make it work. Any help in this aspect would be very much appreciated!

TIA :-)

**Comment by zkytony** [comment]
I've definitely ran it in headless (no-display) mode before. It's been a while so I don't know why `headless` didn't work for you. But you may find the documentation here useful: https://github.com/zkytony/cos-pomdp#to-run-in-ai2thor

**Comment by Ayush8120** [comment]
Hey!
Thanks for the prompt response. I was able to get it running, but wasn't able to render the event frames and instance segmentations. I set the `headless = True` and `x_display = ":0"`. But this made the `event.frame` as `None`.

Is there any way to get it running headless but with  the option of saving the event frames?

**Comment by zkytony** [comment]
Maybe there is, but I've forgotten. Please feel free to investigate a solution.

**Comment by Ayush8120** [comment]
Okay! So I've somehow kind of figured out some ways to save event frames while running a headless execution.

**Method-1:** Upgrade the version to 5.0 and then use the Controller definition given in the docs [here](https://ai2thor.allenai.org/ithor/documentation):
```from ai2thor.controller import Controller
from ai2thor.platform import CloudRendering
controller = Controller(platform=CloudRendering)
```
**Method-2:**(Kind of gets your hands dirty) There is a nice way explained in this Issue's comment  [link](https://github.com/Unity-Technologies/ml-agents/issues/1786#issuecomment-551280552)

[This issue](https://github.com/allenai/ai2thor/issues/105#issue-401874378) also deals with a similar problem and references to the previous link for a solution. {The basic idea is the same as how they made ai2thor executable on colab i.e by using Xorg.}
